version: "3.9"

# build => hangi konfigürasyon dosyası
# multiple php => birden fazla php versiyonuyla çalışabilmek için
# context => hangi konfigürasyon (Dockerfile) dosyası kullanılacak
# image vermeden dockerfile kullanarak da ayağa kaldırabiliriz.
# varsayılan olarak hepsi aynı ağda çalışır ancak bunları farklı ağlar tanımlayıp ayrı şekilde çalıştırabiliriz.


services:
  php7.1:
    image: php:7.1.3-fpm
    build:
      context: ./settings/php7.1
      #dockerfile: istenilen docker file ismi burada belirtilebilir
    hostname: php7.1
    ports:
      - "10001:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./settings/php7.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./settings/php7.1/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php7.3:
    image: php:7.3-fpm
    build:
      context: ./settings/php7.3
      #dockerfile: istenilen docker file ismi burada belirtilebilir
    hostname: php7.3
    ports:
      - "10002:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./settings/php7.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./settings/php7.3/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php7.4:
    image: php:7.4-fpm
    build:
      context: ./settings/php7.4
      #dockerfile: istenilen docker file ismi burada belirtilebilir
    hostname: php7.4
    ports:
      - "10003:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./settings/php7.4/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./settings/php7.4/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8:
    #image: php:8.0-fpm
    #image kullanmadan dockerfile kullanarak ayağa kaldırabiliriz.
    build:
      context: ./settings/php8
      #dockerfile: istenilen docker file ismi burada belirtilebilir
    hostname: php8
    ports:
      - "10004:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./settings/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./settings/php8/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8.2:
    #image: php:8.2-fpm
    #image kullanmadan dockerfile kullanarak ayağa kaldırabiliriz.
    build:
      context: ./settings/php8.2
    hostname: php8.2
    ports:
      - "10005:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./settings/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./settings/php8.2/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ./projects/:/var/www/html/
      -  ./settings/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:  # nginx in bağımlılıkları
      - php7.1
      - php7.3
      - php7.4
      - php8
      - php8.2
    networks:
      - backend
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./settings/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "12345678"
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - backend
networks:  # farklı ağlar oluşturabiliriz
  backend:
    driver: bridge  # bridge => standart
  #new_network:
    #driver: 